trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

# Example: Run linting or static code analysis
- script: |
    npm run lint
  displayName: 'Run code linting'

# Example: Run tests (if you have test scripts set up)
- script: |
    npm test
  displayName: 'Run tests'

# Save build artifacts (optional, if needed for further stages or deployments)
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'

# Example: Deploy step (if you have a deployment pipeline setup)
# This step depends on where you're deploying your app, for instance, to Azure, AWS, etc.
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Your Azure Subscription'
    appName: 'Your Azure Web App Name'
    package: $(System.DefaultWorkingDirectory)/drop/*.zip
  displayName: 'Deploy to Azure Web App'

