---
- name: Configure the M55 Web App
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started
      service:
        name: nginx
        state: started
        enabled: yes
